[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x", "rustc", "cargo", "rustup", "wasm-pack", "gcc", "pkg-config"]

[phases.install]
cmds = [
  "rustup target add wasm32-unknown-unknown",
  "npm ci"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start" 